apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservices
    template:
      metadata:
        labels:
          app: microservices
      spec:
        containers:
          - name: microservices
            image: aw033/solar-system:7b18ec494e457544c9017044b36536e169e7d55b
            ports:
              - containerPort: 3000
            env:
              - name: MONGO_URI
                value: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
              - name: MONGO_USERNAME
                value: ${{ vars.MONGO_USERNAME }}
              - name: MONGO_PASSWORD
                value: ${{ secrets.MONGO_PASSWORD }}