apiVersion: v1
kind: Service
metadata:
  name: microservices
spec:
  selector:
    app: microservices
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer