replicaCount: 3

image:
  repository: 20150748/solar-system
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  MONGO_URI: ""
  MONGO_USERNAME: ""
  MONGO_PASSWORD: ""
