replicaCount: 3

image:
  repository: 20150748/solar-system
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: solar-system-sa

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

mongo:
  uri: ""
  username: ""
  password: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: []

ingress:
  enabled: false
  annotations: {}
  hosts:
  - host: solar-system.example.com
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
