apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AbdullahWahdan/GitAction_SolarSystem.git'
    targetRevision: argo-cd_branch
    path: helm/solar-system-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true