name: solar-system-workflow
on:
  workflow_dispatch:
  push:
    branches:
        - feature_brancheA
        - main
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}

jobs:
  terraform:
        name: terraform-deployment
        #needs: [docker, code-coverage, unit_testing]
        runs-on: ubuntu-latest
        environment: production
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v5
        
        - name: aws login
          uses: aws-actions/configure-aws-credentials@v4.3.1
          with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-east-1

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3.1.2
          with:
            terraform_version: 1.1.7
        
        - name: terraform init
          run: terraform init
          working-directory: ./Terraform/team-01


        - name: terraform plan
          run: terraform plan
          working-directory: ./Terraform/team-01

        - name: terraform apply or destroy
          run: |
              if [ "${{ github.event.inputs.destroy }}" = "yes" ]; then
              terraform destroy -auto-approve
              else
              terraform apply -auto-approve
              fi
          working-directory: ./Terraform/team-01
  
