name: solar-system-workflow
on:
  workflow_dispatch:
  push:
    branches:
        - feature_brancheA
        - main
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}

jobs:
  unit_testing:
    name: unit_testing
    strategy:
      matrix:
        nodejs-version: [18, 19, 20]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        exclude:
        - nodejs-version: 18
          os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v5

    - name: Set up Node.js - ${{ matrix.nodejs-version }}
      uses: actions/setup-node@v4.4.0
      with:
        node-version: ${{ matrix.nodejs-version }}

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      id: nodeNodeJs-unit-testing-step
      run: npm test

    - name: archive test results
      if: steps.nodeNodeJs-unit-testing-step.outcome == 'failure' || steps.nodeNodeJs-unit-testing-step.outcome == 'success'
      uses: actions/upload-artifact@v4.6.2
      with:
        name: sp-test-results-${{matrix.os}}-${{matrix.nodejs-version}}
        path: test-results.xml

  code-coverage:
    name: code-coverage
    needs: unit_testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Set up Node.js - 18
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: check Code Coverage
        run: npm run coverage
      
      - name: archive Coverage results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: code-coverage-results
          path: coverage
          retention-days: 5
